<html> <img style="float:center; margin: 0px 0px 0px 0px;" src="https://docs.google.com/uc? export=download&id=1JDfKEyqZsOrv8tZrgeIDJFQ_c_W0LF-K" width="370" align="left"/> </html> 


<center> <H1> <b>Data Analysis with Python </b><figure> </H1> </center>
<center> <H6>  </H6> </center>



# Data Transformation in Pandas

In [ ]:
import pandas as pd

In [ ]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [ ]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [ ]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [ ]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [4]:
import pandas as pd
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [5]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [6]:
df["names"]

0     Tim
1     tom
2     Sam
3    kate
4     Kim
Name: names, dtype: object

In [7]:
Names=df["names"].str.capitalize()

In [8]:
df["branches"]=Names.map(classes)

In [9]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

What is the difference between map(), applymap() and apply() methods in pandas? 

- In pandas, all these methods are used to perform either to modify the DataFrame or Series. 
- **map**() is a method of Series, **applymap**() is a method of DataFrame, and **apply**() is defined in both DataFrame and Series.

What is the difference between apply and Applymap in pandas?

- apply() is used to apply a function along an axis of the DataFrame or on values of Series. 
- applymap() is used to apply a function to a DataFrame elementwise.

In [ ]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [ ]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [ ]:
import numpy as np

In [ ]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [ ]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [ ]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [ ]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [ ]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [ ]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [ ]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [ ]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

## pandas cut() 

In [ ]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [ ]:
x=[20,40,60,80,100]

In [ ]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [ ]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [ ]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [ ]:
pd.value_counts(y)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [ ]:
nm=["low", "medium", "high", "very high"]
y= pd.cut(sc,x,labels=nm)

In [ ]:
y

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [10]:
sc

''

In [ ]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] <
                                            (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] <
                                            (86.0, 93.0] < (93.0, 100.0]]

## qcut

In [20]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(-0.607, 0.251], (-0.607, 0.251], (-0.607, 0.251], (-2.6879999999999997, -0.607], (-0.607, 0.251], ..., (0.251, 0.754], (-0.607, 0.251], (-0.607, 0.251], (-2.6879999999999997, -0.607], (-2.6879999999999997, -0.607]]
Length: 100
Categories (4, interval[float64, right]): [(-2.6879999999999997, -0.607] < (-0.607, 0.251] < (0.251, 0.754] <
                                           (0.754, 2.473]]

In [21]:
c

[(-0.607, 0.251], (-0.607, 0.251], (-0.607, 0.251], (-2.6879999999999997, -0.607], (-0.607, 0.251], ..., (0.251, 0.754], (-0.607, 0.251], (-0.607, 0.251], (-2.6879999999999997, -0.607], (-2.6879999999999997, -0.607]]
Length: 100
Categories (4, interval[float64, right]): [(-2.6879999999999997, -0.607] < (-0.607, 0.251] < (0.251, 0.754] <
                                           (0.754, 2.473]]

In [19]:
type(c)

pandas.core.arrays.categorical.Categorical

In [16]:
import numpy as np
np.random.randn()

-0.2787616659763774

In [ ]:
data

array([-1.6088859 ,  0.53732284, -1.16471271,  1.50252682, -1.00198063,
        0.51018319,  0.09181993,  0.04317682,  0.31932418,  0.19163488,
        1.38862592, -0.77103245,  2.04995715, -0.52439376,  2.09990588,
        1.27146964,  0.49330165,  0.82950496, -0.0173636 , -1.40442977,
       -1.38718532, -0.11158239,  1.77870875,  0.284519  , -0.16774943,
       -1.07509663, -0.60978594,  0.51326112,  1.25877574, -1.77783386,
       -0.42462781,  0.0410419 ,  0.82405472,  1.82137719,  1.24981823,
       -1.51897404,  0.44386191,  0.15342412,  0.38200515,  1.43877345,
       -0.42600771, -0.94263866, -0.43851718,  0.74802826,  0.11920992,
       -0.64951557, -0.4597438 ,  0.62095037,  0.37952826,  1.17728179,
       -0.1853829 ,  0.27366764, -1.3430225 , -0.36438881, -0.43306728,
        1.014869  ,  1.15589157,  0.67325069,  1.66605099, -0.74008415,
       -0.29314915,  1.16325331, -0.68305685,  2.35873753,  0.9209693 ,
        0.26786084,  1.00701914,  0.62533641, -0.40701205,  0.13

In [ ]:
pd.value_counts(c)

(-2.0469999999999997, -0.527]    25
(-0.527, 0.143]                  25
(0.143, 0.927]                   25
(0.927, 2.359]                   25
dtype: int64

## Dummy Variable

In [ ]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [ ]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [ ]:
data=np.random.randn(10)
data

array([-1.41808811,  1.45723562, -0.32625889, -1.13659509,  2.17562767,
       -0.73801607, -1.74597064,  0.32088976, -0.18373379, -2.02214278])


**get_dummies**() is used for data manipulation. It converts categorical data into dummy or indicator variables.

In [ ]:
pd.get_dummies(pd.cut(data,4))

(-2.026, -0.973]  (-0.973, 0.0767]  (0.0767, 1.126]  (1.126, 2.176]
0                 1                 0                0               0
1                 0                 0                0               1
2                 0                 1                0               0
3                 1                 0                0               0
4                 0                 0                0               1
5                 0                 1                0               0
6                 1                 0                0               0
7                 0                 0                1               0
8                 0                 1                0               0
9                 1                 0                0               0